development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sigre_development
  pool: 5
  username: root
  password: 
  #socket: /usr/local/var/mysql/mysql.sock

development_netmultix:
  adapter: oracle_enhanced
  database: //10.1.0.44:1521/cimavXDB.netmultix.cimav.edu.mx
  username: almacen
  password: afrika
  pool: 10

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sigre_test
  pool: 5
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sigre_production
  pool: 5
  username: root
  password: 

production_netmultix:
  adapter: oracle_enhanced
  database: //10.1.0.44:1521/cimavXDB.netmultix.cimav.edu.mx
  username: almacen
  password: afrika
  pool: 10
